# Generated by Django 5.1 on 2024-08-21 12:12

import django.contrib.postgres.indexes
import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductForReview',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.product',),
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcuts', to='marketplace.productsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.style'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('position', 'order'), name='positions_unique_ordering'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='marketplace_title_506a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='marketplace_price_34d50e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published'], name='marketplace_publish_97600d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='marketplace_search__46b30c_gin'),
        ),
    ]
