# Generated by Django 5.1 on 2024-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selling_access',
            field=models.BooleanField(default=True, help_text='Access for selling'),
        ),
    ]
